services:
    # Left here for retrocompability
    rubenrubiob_simple_api_caller:
        class: rubenrubiob\SimpleApiCallerBundle\Service\SimpleApiCallerService
        arguments:
            cacheDir: "%kernel.cache_dir%"

    rrb.simple_api_caller:
        class: rubenrubiob\SimpleApiCallerBundle\Service\SimpleApiCallerService
        arguments:
            cacheDir: "%kernel.cache_dir%"
